set(DIRECTXMATH_INCLUDE_DIR 
${CMAKE_SOURCE_DIR}/External/DirectXMath/Inc
)

file(GLOB_RECURSE DIRECTXMATH_SOURCE    
"${CMAKE_SOURCE_DIR}/External/DirectXMath/*.h"
"${CMAKE_SOURCE_DIR}/External/DirectXMath/*.cpp"
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(DIRECTXMATH DEFAULT_MSG
DIRECTXMATH_INCLUDE_DIR DIRECTXMATH_SOURCE)