name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Release]
        compiler: [MSVC, Clang]

    steps:
    - uses: actions/checkout@v4

    - name: Install Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: 1.4.304.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: false

    - name: Configure CMake
      shell: pwsh
      run: |
        $generator = "Visual Studio 17 2022"
        if ($env:ImageVersion -like "*2025*") {
          $generator = "Visual Studio 18 2026"
        }
        
        if ("${{ matrix.compiler }}" -eq "Clang") {
          cmake -B build -S . -G $generator -A x64 -T ClangCL -DCONV_USE_CLANG_CL=ON
        } else {
          cmake -B build -S . -G $generator -A x64 -DCONV_USE_CLANG_CL=OFF
        }

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --target Convolution
